# Generated by Django 3.0.3 on 2020-04-14 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200414_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 22, 20, 36, 847824)),
        ),
    ]
