# Generated by Django 3.0.3 on 2020-04-14 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200414_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 0, 20, 49, 926325)),
        ),
    ]
