# Generated by Django 3.0.3 on 2020-04-14 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200415_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='complete',
            new_name='mark',
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 0, 21, 59, 959826)),
        ),
    ]
