# Generated by Django 3.0.3 on 2020-04-15 14:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20200415_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 15, 47, 42, 293324)),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='username',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
