# Generated by Django 3.0.3 on 2020-04-15 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200415_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 15, 51, 31, 963326)),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='username',
            field=models.CharField(default='', max_length=25),
        ),
    ]
