# Generated by Django 3.0.3 on 2020-04-15 15:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0014_auto_20200415_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 16, 15, 56, 673825)),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
