# Generated by Django 3.0.3 on 2020-04-15 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200415_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 21, 51, 1, 524325)),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
